### ISSUE TITLE
건물에 속하는 층들 중 가장 최근에 추가한 층을 리턴해주는 FloorController.getLatestFloor()가 올바로 작동하지 않음.

### ISSUE THREAD

**Issue by AhnHyeonho** [hancom-io/hanzari#1038]
건물을 고려하지않고 floorOrder(가장 최근에 삽입된 층)가 리턴되는 문제가 발생.

`ex. HANCOM01건물에 floorOrder최대값은 4, HANCOM02건물에 floorOrder최대값은 5인 상황에서 HANCOM01건물에 대한 getLatestFloor()가 불렸는데 HANCOM02의 층 중 floorOrder최대값이 5인 층이 리턴되는 문제 발생.  `

**Comment by hnc-cjcho** [comment]
문제 상황을 자세히 설명해 준것에 대해서 👍
