### ISSUE TITLE
DB 저장 완료 시점 알아내기

### ISSUE THREAD

**Issue by cyj2857** [hancom-io/hanzari#1049]
실제로 1층~10층 까지의 60개 좌석을 배치하고 저장 해보는 기능 테스팅을 해본 결과,

실제로 저장이 되지 않았는데 중간에 로드를 할 시에 정보가 다 저장이 되지 않은 것을 확인했다

**Comment by hnc-cjcho** [comment]
👍 이슈에 자세한 설명 상당히 좋습니다. ^_^
