### ISSUE TITLE
사용자가 로그인중인 상태에서 토큰 만료시에 refresh 토큰하여 세션 유지

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#1165]

**Comment by yunji98** [comment]
현재 로그인 되어있는 사용자가 서비스 사용 도중 토큰이 만료되면 403 에러가 뜨며 
데이터를 가져오지 못합니다. 하지만 페이지 이동은 가능한 상태이기 때문에

1. 페이지 이동을 막고 로그인 다시 요구
2. 토큰 재발급 이후 세션 유지

위의 두 방법중 상의후 처리 방법을 결정해야할 것 같습니다.

**Comment by hnc-cjcho** [comment]
가능하다면 이슈를 만들때 위 내용을 미리 적어 주세요~ ^_^
