### ISSUE TITLE
크리티컬한 기준(사용자가 복구할 수 없는 상태 변경시) 논의 후 경고창 생성하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#1166]

**Comment by yunji98** [comment]
1. 사용자가 자리를 삭제하는 경우
2. 사용자가 CSV 파일 업로드하는 경우
3. 사용자가 매핑된 자리를 자리비우기 하는 경우
4. 사용자가 자리를 층간이동 하는 경우
5. 사용자가 이미 매핑된 자리에 또 매핑하려 하는 경우
6. 관리자가 사원의 권한을 변경하는 경우
7. 자리 선택안하고 3, 4 번 하는 경우 
+ 자리 선택안하고 매핑하려는 경우 
+ 도면에 공석 아무것도 없이 매핑하려는 경우 
8. 층 없이 이미지 올리는 경우
9. 층 없이 자리 생성하는 경우
10. 층 이름 없이 자리 생성하는 경우
11. 로그아웃 하기 전
12. 로그아웃 성공시

**Comment by yunji98** [comment]
dialog
1, 2, 3, 4, 5, 6, 11, 13
toast
8, 9, 10, 12

**Comment by yunji98** [comment]
논의 결정되었으므로 comment 참고하여 #1168 진행하겠습니다.
본 이슈는 close하도록하겠습니다.

**Comment by hnc-cjcho** [comment]
12번 로그아웃을 성공하는 경우에는, 혹시 현재 페이지를 벗어나, 최초 화면으로 이동하지 않나요?
그렇게 되면, 최초화면에서 "로그아웃에 성공하였습니다." Toast로 보여 줄 것인지요?

**Comment by yunji98** [comment]
로그아웃을 성공하는 경우에 최초 화면으로 이동하게 됩니다.
만약 12번을 진행한다면 최초화면에서 "로그아웃에 성공하였습니다"를 띄워주려했지만 

기존 네이버나 구글같은 사이트에서 로그아웃 할 시에 어떤 팝업창도 띄우지 않는 것을 보고 로그아웃 전에 사용자의 의사만 물어보는 11번만 구현하거나 어떤 창도 띄우지않고 로그아웃 시킬 예정입니다.
