### ISSUE TITLE
ctrl 키 누르고 복수 자리 선택 가능하게 하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#1274]
현재는 복수 자리를 선택하려면 드래그해서 셀렉션하는 방법이 유일합니다.

★ ctrl키를 누른후부터 기능이 동작한다.

**Comment by hyori100** [comment]
★setCtrlKeyPressedForMultiSelection() - ctrl키 누르고 도형 선택시 복수선택 할 수 있는 기능을 구현해놓은 메소드

-> **selection:created**(초기 도형이 select된 시점)의 도형 객체를 하나의 리스트에 push하기
      this.floorCanvas.on("selection:created", (event) => {
        ...
          event.selected.forEach((selectedObject) => {
            if (!multiSelectionObjectList.includes(selectedObject)) {
              multiSelectionObjectList.push(selectedObject);
            }
          });
      });

-> **selection:updated**(selection이 바뀌어진 시점)의 도형 객체를 기존 리스트에 push하기
      this.floorCanvas.on("selection:updated", (event) => {
        ..
          event.selected.forEach((selectedObject) => {
            if (!multiSelectionObjectList.includes(selectedObject)) {
              multiSelectionObjectList.push(selectedObject);
            }
          });
        ..
        this.floorCanvas.discardActiveObject(); //자동으로 "selection:cleared"가 호출됨
      });

-> **selection:cleared**(select된 도형이 없는시점)에서 selection:created와 selection:updated를 거쳐 만들어진 리스트를 화면에 표출하기

      this.floorCanvas.on("selection:cleared", (event) => {
        ...
            activeSelection = new fabric.ActiveSelection(
              multiSelectionObjectList,
              {
                canvas: this.floorCanvas,
              }
            );
            this.floorCanvas.setActiveObject(activeSelection);
            this.floorCanvas.requestRenderAll();
      });
