### ISSUE TITLE
root directory에 있는 .project 파일과 .classpath 파일 제거해 주세요.

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#185]
해당 파일은 아마도 eclipse에서 사용하는 설정 파일일 것입니다.
그러므로 backend 사람에게만 필요한거 맞나요? ㅎ
그러니 해당 파일이 root에 있으면 안됩니다.

backend 디렉토리에서도 프로젝트를 eclipse에 import 할 때,
settings.gradle나 build.gradle 파일로 import 가 가능할 것입니다.
그러므로, backend 디렉토리에도 .project파일과 .classpath 파일이 필요 없을것입니다.

만약 두개의 파일이 없을때 이클립스에서 import 할 줄 모른다면, 어쩔 수 없이 넣어야 겠지만,
할 줄 안다면 두 파일을 제거해 주세요.

**Comment by AhnHyeonho** [comment]
해당이슈 처리하였습니다.

**Comment by DongminKim94** [comment]
완료하였습니다.
