### ISSUE TITLE
Vue에서 현재 층 이미지 로드한뒤 다른 층 이미지 로드하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#195]

**Comment by cyj2857** [comment]
1. axios.post에서 파일 형식을 보낸다

**Comment by cyj2857** [comment]
2. fabric.Image.fromURL에서 url 이미지 주소를 받는다.

**Comment by cyj2857** [comment]
**axios.get
1. {건물/건물id/층/층id} api에서 이미지 url를 받아옵니다.
2. initimagelist에서 이미지 url 정보를 저장합니다.
3. 이미지 url을 캔버스 배경화면에 설정합니다.

**Comment by cyj2857** [comment]
*axios.post
1. 이미지 파일을 multipart-fomdata 형태로 변환합니다.
2. 파일 형식을 api로 보내줍니다.
3. allfloorimagelist에 파일 형식을 저장합니다.
