### ISSUE TITLE
사용자가 원하는 정보 선택해서 자리 배치도 프린트하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#204]

**Comment by hnc-cjcho** [comment]
해당이슈를 구현해서 close 시킨건가요? 아니면, 해당 이슈를 구현하지 않기로 결정해서 close 시킨 건가요?
아무런 기록없이 close 되어 있습니다. Reopen 시킵니다.

**Comment by yunji98** [comment]
이미 Done인 #503 자리배치도 프린트하기 이슈와 중복되는 이슈로 판단하여 close 시켰습니다.

**Comment by hnc-cjcho** [comment]
그런 이유도 적어 두셔야 해요. 아니면 이슈에 대한 추적을 할 수 없습니다. ^_^
앞으로는 잘 적어 주세요.

**Comment by yunji98** [comment]
넵 앞으로 주의하겠습니다!
