### ISSUE TITLE
Vue에서 axios POST 기능을 이용한 현재층의 자리 save를 여러 층 자리들도 한꺼번에 save되게하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#218]
여러 층에 대한 자리 정보가 저장 버튼을 누를시 한꺼번에 DB에 저장됨.

**Comment by yunji98** [comment]
여러 층에 대한 자리 정보가 저장 버튼을 누를시 한꺼번에 DB에 저장됨.

**Comment by hyori100** [comment]
여러 층에 대한 자리 정보가 저장 버튼을 누를시 한꺼번에 DB에 저장됨.
