### ISSUE TITLE
필드로 관리하기 (modify, delete, create)

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#280]
현재는 세개의 리스트로 관리되고 있음.

**Comment by cyj2857** [comment]
1. 자리 객체에 create/delete/modify를 만들었습니다.
2. 이 필드들은 true와 false로 되어있습니다.
3. 객체가 변경될때(object:modified) delete를 true로 바꿔줍니다.(크기, 위치, 각도) 
  + 사원 자리 매핑/ 자리 비우기도 delete를 true로 바꿉니다.
4. 객체가 생성될때 create를 true로 설정했습니다.
5. 객체가 삭제될때 delete를 trur로 설정했습니다.

**Comment by cyj2857** [comment]
if (groupToObject.create == false) {
                if (groupToObject.delete == true) {
                  //axios.delete
                } else if (groupToObject.modify == true) {
                  //axios.post
                }
              } else {//groupToObject.create == true
                if (groupToObject.true == false) {
                  break;
                } else {
                  //axios.post
                }
              }
//이 형식으로 axio를 호출하도록 합니다.

**Comment by cyj2857** [comment]
6. seatData의 create/delete/modify를 false로 설정함(초기화하기 위해서입니다.)

**Comment by yunji98** [comment]
층은 ManagerFloorList를 더 추가하여 가시적 리스트와 관리 리스트(DB와 저장, 로드할)를 생성하여 필드로 관리하는데에 성공을 했습니다. 하지만 자리는 처음 층에 해당되는 seatlist가 하나 더 생겨서 지연되는 중입니다.

**Comment by yunji98** [comment]
구조에 맞게 로직은 짜두었으나 api가 구성되지 않아서 아직 test해보지 못한 단계입니다.

**Comment by yunji98** [comment]
api 대부분 구성되어 test해보았습니다.
이후 문제 발견시 새로운 issue로 올리겠습니다.
Done으로 옮기겠습니다.
