### ISSUE TITLE
MinIO 서버로 파일 전송을 위한 백엔드 코드 작성

### ISSUE THREAD

**Issue by DongminKim94** [hancom-io/hanzari#284]
Backend 코드 작성 완료
프론트엔드에서 FormData 형식을 이용하여(Key, Value로 이미지를 담아주어) axios로 이미지 전송 성공
백엔드로 받아 온 이미지를 MinIO 서버로 전송한 뒤 스토리지에 저장하는 기능까지 구현

**Comment by DongminKim94** [comment]
Backend 코드 작성 완료
프론트엔드에서 FormData 형식을 이용하여(Key, Value로 이미지를 담아주어) axios로 이미지 전송 성공
백엔드로 받아 온 이미지를 MinIO 서버로 전송한 뒤 스토리지에 저장하는 기능까지 구현

**Comment by hnc-cjcho** [comment]
다음에는 pull requests 연결 해 놔 주세요~ ^_^

**Comment by DongminKim94** [comment]
네 다음부터는 연결하도록 하겠습니다.

**Comment by DongminKim94** [comment]
> 다음에는 pull requests 연결 해 놔 주세요~ ^_^
네 다음부터는 연결하도록 하겠습니다.
