### ISSUE TITLE
Vue에서 화면이 시작될때 처음 보여지게 되는 층에 해당되는 자리불러오기

### ISSUE THREAD

**Issue by hyori100** [hancom-io/hanzari#291]
기존 구조인 모든 seats를 한번에 받아오는 구조를 바꾸는 작업.

처음 보이는 층만 먼저 axios를 통하여 불러오고 나머지 층에 대한 자리들은 axios를 통하여 기존 리스트에 보관한다. 
그 층의 탭이 클릭될때마다 기존 리스트에서 자리들을 가져와 화면에 렌더링한다.

**Comment by yunji98** [comment]
Admin.vue에 있는 getCurrentFloorSeats의 파라미터로 currentFloorId 를 넣어주고 curretFloorSeats를 넘기는 방법을 찾았지만 파라미터를 넘겨주는 시점이 changeFloor eventBus를 받을 때여서 층이 늘어날때마다 불리는 문제점을 발견했습니다.
정보 load를 순차적으로 처리하기 위해 비동기 동기 처리인 async await 방법을 사용해야할 것 같습니다. (employee -> floor -> image -> seat)

**Comment by yunji98** [comment]
async await로 처리하면서 eventBus가 더 빨리 불리는 문제를 발견하여 eventBus 말고 다른 방법을 사용할 예정입니다.

**Comment by yunji98** [comment]
층들이 성공적으로 다 불리게되면 그 이후 sort 과정을 실행하기 때문에 현재의 층의 이름과 id를 eventbus를 사용하지 않고도 사용할 수 있게 되었습니다.

**Comment by yunji98** [comment]
load버튼을 누르면 그때 현재층의 자리 리스트만 뜨게 수정하였습니다.
현재 층의 자리 리스트가 뜨는 것이 성공하면 이후에 다른 층들의 자리 리스트를 로드해서 리스트로 불러오게 구현할 것입니다.

**Comment by yunji98** [comment]
getOtherFloorSeats 함수를 추가하여 현재 자리 리스트가 뜨는데에 성공하면 이후에 다른 층들의 자리 리스트들을 로드해서 리스트로 불러오게 구현하였습니다. 이는 이후 테스트할 예정입니다.

**Comment by yunji98** [comment]
시작시 DB에 있는 현재층의 자리들만 load 되는 것 확인하여 Done으로 옮기겠습니다.
