### ISSUE TITLE
xxxxByAxios 라는 이름을 사용하지 말아 주세요. ( Axios 말고 다른것 찾아 볼 것 )

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#299]
Axios 이외의 http 라이브러리를 사용하면 해당 event의 이름을 또 바꿔야 합니다.
그러므로 "의미기반"으로 이름을 정해 주세요.

**Comment by yunji98** [comment]
수정하였습니다. 관련 pr은 link해두었습니다.
