### ISSUE TITLE
getSeatUUID 를 호출할때마다 다른 값이 나옵니다. 이건 get이 아니라, create 나 new 입니다.

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#301]
https://github.com/hancom-io/hanzari/blob/af2c0af9b734dc65bddbe6a0216e7898a3beb2f7/HanzariProject/frontend/src/components/AttachCanvas.vue#L218

해당 함수는 항상 다른 값이 나오도록 되어 있습니다.
그러므로 getSeatUUID라는 이름을 사용하면 오해할 수 있습니다.

get-"얻어 오는"이 아니라, create-"생성 하는" 정도의 개념이 되어야 합니다.
매번 새로 생성하므로 "create new" 정도의 개념이 되어야 할 것입니다.

그러므로 이름을 정한다면, createSeatUUID 혹은 createNewSeatUUID 가 정도가 되어야 합니다.
만약 제가 이해한 내용이 틀렸다고 하더라도 "get"은 의미가 맞지 않으니, 이름을 적절히 바꿔 주세요.

**Comment by cyj2857** [comment]
네 저도 함수 명칭이 적절하지 않다고 생각합니다. createSeatUUID로 수정했습니다!

**Comment by hnc-cjcho** [comment]
수정했으면, 수정한 pull requset 달아 주세요~ 그리고 자동으로 닫히지 않는다면 닫아 주기도 해 주세요~
