### ISSUE TITLE
Input/OutputStream들을 잘 닫아야 합니다.

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#312]
https://github.com/hancom-io/hanzari/blob/dfd71f7e8a1df699b16680f2b1b1bebc6530bb29/HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/TestImageController.java#L45

이곳에서 만들어진 InputStream은 언제 닫히나요?
InputStream이 타고타고타고타고 들어가 보니깐, File이랑 연결되어 있다면...

InputStream에서 데이터를 읽으려고 하면, 결과적으로 File에서 데이터를 읽어야 할 꺼고,
그렇다면 File은 Open  된 상태일것입니다.
한개의 process에서 사용할 수 있는 File descriptor 갯수는 제한이 있습니다.
이런식으로 File을 계속 Open 시켜두면, 언젠가는 서버에서 더 이상 파일을 읽고 쓰지 못하는 문제가 발생할 수 있습니다.
( 네트워크 소켓도 마찬가지로 내부에서는 File descriptor 를 만들어서 처리하게 되므로, socket도 잘 close 시켜줘야 합니다. )

그렇게 되면 당연히 서버가 오동작을 하겠죠?
그러므로 Input/OutputStream 혹은 Reader/Writer는 무조건 쌍이 잘 맞는지 확인해야 합니다.

https://github.com/hancom-io/hanzari/blob/dfd71f7e8a1df699b16680f2b1b1bebc6530bb29/HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/TestImageController.java#L61

위 코드도 마찬가지입니다.
minioService.upload를 할 때 param으로 file의 inputstream을 만들어서 넘기는데요.
저기서 만들어진 inputstream은 누가 닫아 주나요? 
minioService.upload가 내부적으로 알아서 닫아 주나요? ( 당근 그럴리 없겠죠? )

수정해 주세요.

**Comment by DongminKim94** [comment]
네 팀장님. 피드백 주신 내용 유의하여 코드 작성하도록 하겠습니다.(현재 작성한 코드는 프론트엔드 ~ 백엔드 ~ MinIO 서버가 잘 연결 되는지 확인하기 위해 구글을 참고하여 임시로 작성한 코드입니다. 다음주에는 공식 API인 MinioClient 클래스의 메소드들을 이용하여 필요한 기능 구현하도록 하겠습니다.)

**Comment by hnc-cjcho** [comment]
넵 문제가 해결 되었다면 해당 이슈 close 처리해 주세요~
