### ISSUE TITLE
frontend의 key, floor_name에서 floor_id로 변경하기

### ISSUE THREAD

**Issue by AhnHyeonho** [hancom-io/hanzari#325]
현재 frontend에서 key를 floor_name으로 가지고 있는데 이는 개념과 맞지 않다고 판단되기에 floor_id를 key로 하는 구조로 수정하겠습니다. 가시적인 층은 floor_name을 사용하고 구조적으로는 floor_id를 사용할 예정입니다.

**Comment by yunji98** [comment]
현재 층간 이동을 제외하고 이전과 같게 관리되게 하였습니다. 층간 이동은 층을 입력받는 형식이 아니라 key를 바탕으로 한 셀렉트 박스 등으로 구현을 할 예정입니다.

**Comment by yunji98** [comment]
층간 이동 가능하게 하였습니다. front의 자리 key 모두를 floor_id로 바꾸어서 Done으로 옮기겠습니다.
