### ISSUE TITLE
BE 부하테스트를 위한 JMeter 준비하기

### ISSUE THREAD

**Issue by AhnHyeonho** [hancom-io/hanzari#564]

**Comment by hnc-cjcho** [comment]
서버를 테스트 할 때는 서버의 사양을 변경해 가면서 테스트 해야 합니다.
docker container는 cpu 사용량, ram 크기를 제한해서 container를 띄울 수 있으므로,
이를 변경해 가면서 테스트 해 보세요.

만약 수평확장(backend 서버가 여러개가 되어도 동작할 수 있도록 만들어 진 상태)이 가능하다면,
서버 갯수, cpu 사용량, ram 크기 3개를 모두 조합해서 테스트 해 봐야 합니다.

더 정확하게 하려면 JMeter를 돌리는 서버를 외부에 두는것이 좋습니다.
JMeter가 동작하는것 자체도 컴퓨터의 CPU를 사용하게 되므로 영향을 받을 수 있기 때문입니다.

어느 수준까지 해 볼 건지는 판단해서 정해 주세요.

**Comment by AhnHyeonho** [comment]
@hnc-cjcho // 관련하여 질문이 있습니다. 
1. 수평확장이 가능한 상태(현재 nginx를 돌리고 있고, 동일한 백엔드서버이미지로부터 여러 컨테이너를 생성 가능한 상황)인데, 혹시 같은 pc에서 컨테이너를 여러 개 생성해도,
 `더 정확하게 하려면 JMeter를 돌리는 서버를 외부에 두는것이 좋습니다. JMeter가 동작하는것 자체도 컴퓨터의 CPU를 사용하게 되므로 영향을 받을 수 있기 때문입니다.` 이 의견과 비슷한 이유로 같은 컴퓨터에서 돌아가고 있는 상황이라 서버 갯수를 늘리면서 테스트해봐야 한다는 말씀은 n대의 PC에 컨테이너를 따로 띄우고 nginx로 묶어서 테스트 하는 걸 의미하는 게 맞나요?

2. `cpu 사용량, ram 크기`를 각각 어떤식으로 테스트해봐야하는 것인지 정확하게 모르겠습니다. 예를 들면 초당  몇 회의 요청에 대해서 처리할 수 있는 최소한의 하드웨어 사용량을 찾기 위한 과정인건가요?

**Comment by AhnHyeonho** [comment]
답변을 받아 대신 적어두도록 하겠습니다.

```
1번 답변 드립니다.
docker container를 띄울때 cpus 옵션등을 이용하면 컨테이너가 사용가능한 자원을 제약할 수 있습니다.
하지만 그를 테스트 하는 JMeter는 docker 기반이 아니라, cpu 사용량을 제한할 수 없을 것입니다.
그러므로 JMeter가 cpu를 모두 사용해 버리려고 하면, docker container가 사용하려고 하는 cpu time과 경쟁하는 문제가 생길것입니다.
그러므로 JMeter를 "분리 할 수 있는 환경"에서 테스트하는데 신경을 써야 한다는것입니다.
JMeter 자체도 container로 만들어서 테스트 할 수도 있겠지만, container 를 사용함으로 인해서 발생하는 부하도 있을 수 있습니다.
이는 무시할 만한 수준이라고 생각되지만, 그래도 좀 더 정확하게 하려면, 두개를 모두 테스트 해 보는게 좋겠죠?
( container system은 native system에 비해서 얼마나 느린가를 "직접" 측정해 보는것도 경험이 되리라 생각합니다. )
```
```
2번부터 답변 드립니다.
docker container를 띄울때 아무런 옵션이 없다면, 아마도 RAM은 "필요한 만큼"만 사용하겠지만.
cpu의 사용량을 제한하지 않으면, 모든 core를 다 사용하려고 할 것입니다.
만약 부하가 많이 걸리는 일을 하게 된다면, core가 많은 장비와 적은 장비와의 속도차이가 발생할 것입니다.
그렇게 되면 초당 몇 회를 처리하는 기준이 달라 질 수 있습니다.
그러므로 내 프로그램의 사양을 측정하려면, 정확한 스펙이 필요합니다.
그러기 위해서 docker container를 띄울때 --cpus 같은 옵션을 사용해서 cpu 사용량을 제약한 뒤에 테스트 해 보라는것이었습니다.
특히 RAM의 사용량은 반드시 체크 되어야 합니다.
최소는 크게 의미가 없습니다. 동작하는 적정량이 필요합니다. 그 적정량의 기준은 직접 정해야 합니다. ( 사용하는데 느리지 않다고 느끼는 기준? )
예를 들면, 지금 한컴그룹의 모든 자리를 관리하고, 눌렀을때 평균 0.2초~0.3초 이내의 응답을 정하던지 하면 될 듯 합니다.
( 네트워크 문제로 느린것은 어쩔 수 없지만, DB Query 가 느린것들은 개선이 필요하겠죠. )
참고로
kubernetes에는 Compact 가능한 Resource라는 개념이 있습니다.
예를 들어 CPU 의 경우에는 설정량 보다 많은 부하가 걸리면 "느리게라도 동작" 합니다.
하지만, RAM의 경우에는 설정량 보다 많은 부하가 걸리면 "OOM-Out of memory"가 발생하면서 프로그램이 죽게 되죠.
CPU는 Compact 가능한 Resource이며, RAM은 Compact 불가능한 리소스가 됩니다.
```
