### ISSUE TITLE
AttachCanvas.vue 파일 이름 변경 요청 - 의미를 가지는 이름으로...

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#688]
AttachCanvas.vue 관련 내용을 보니, 이제 걔가 해야 할 일들이 명확해 진 듯 합니다.
그렇다면 그 vue 파일의 이름이 좀 더 명확한 이름을 가질 수 있도록 하는게 좋을듯 합니다.

Class나 file이름 혹은 그것들의 개념이 변경되면,  다른 사람들이 혼동할 수 있습니다.
그러므로 긴급하지 않은 일이라면 다른 사람들에게 이름 변경을 공지한 후, 얼마후 변경해 주세요.
얼마후의 기준은 "다른 이름이나 개념으로 이야기해도 알아 들을 수 있을 정도의 기간" 으로 잡으면 됩니다.

그러려면, 공지를 하고 그 용어를 몇번 정도는 들어봐야 듣는 상대편도 편하게 인지할 수 있겠죠?
만약 모두에게 명확하게 공지 되고, 다른사람도 한번에 잘 인지 했다면 바로 변경해 주셔도 됩니다.

**Comment by yunji98** [comment]
네 확인했습니다.

**Comment by yunji98** [comment]
자리를 배치 및 자리에 사원 배치 역할을 하는 컴포넌트이기 때문에 AssignSeats.vue 로 이름 변경하겠습니다.
