### ISSUE TITLE
비교시에 동등 연산자(==) 대신 일치 연산자(===) 사용하기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#796]
동등 연산자(==)는 형변환을 해서 비교를 하기에
1 = ='1' 
true == 1
undefined == null 
위의 return 값은 모두 true가 된다.

반면 일치 연산자는(===)는 형변환을 하지 않고 연산하기 때문에
위의 return 값이 모두 false가 나오며 더 정확한 비교가 가능해진다.

**Comment by AhnHyeonho** [comment]
assignee추가해주세요~
