### ISSUE TITLE
층 저장 구조 재설계

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#873]
객체(층, 좌석) 필드 :
 - 이미 DB에 저장되어 있는 객체인지를 알 수 있는 'isObjFromDB' 필드
   (type : boolean / value : true, false)
 - 최종적으로 저장될 때 AXIOS http request를 정해줄 'httpRequestDecisionStatus' 필드
    객체에 행해진 마지막 행위를 기준으로 value가 정해진다.
   (type : string / value : 'delete' , 'post', null)
1. DB에 저장된 객체를 프론트로 로드해 올 때 ('isObjFromDB' 필드 true)
 'httpRequestDecisionStatus' 필드 null
2. 객체가 프론트에서 새로 만들어질 때 ('isObjFromDB' 필드 false)
'httpRequestDecisionStatus' 필드는 모두 'post'
3. 객체 삭제
'isObjFromDB' 필드가 true면 'httpRequestDecisionStatus' = 'delete'
'isObjFromDB' 필드가 false면 리스트에서 remove()
4. 객체 수정시
'httpRequestDecisionStatus' = 'post'

====>  저장 과정 (흐름)
1. 리스트에서 'httpRequestDecisionStatus' 가 'delete '면 Axios를 이용하여 delete http 요청
2. 리스트에서 'httpRequestDecisionStatus'가 'post'면 Axios를 이용하여 post http 요청
결론적으로 httpRequestDecisionStatus 필드가 null인 경우를 제외하고 axios http request를 하게 됩니다.

**Comment by hnc-cjcho** [comment]
👍  이슈에 코멘트를 잘 달아 줬습니다.
