### ISSUE TITLE
Http request에서 redirection 관련 설정이 있는데, 이것을 왜 설정하신거죠?

### ISSUE THREAD

**Issue by hnc-cjcho** [hancom-io/hanzari#898]
https://github.com/hancom-io/hanzari/blob/56322ff4b8a622a64bfe6d83426b44146273b7bf/HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/BatchEmployeeUpdateConfiguration.java#L107

**Comment by DongminKim94** [comment]
> https://github.com/hancom-io/hanzari/blob/56322ff4b8a622a64bfe6d83426b44146273b7bf/HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/BatchEmployeeUpdateConfiguration.java#L107

**Comment by DongminKim94** [comment]
> https://github.com/hancom-io/hanzari/blob/56322ff4b8a622a64bfe6d83426b44146273b7bf/HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/BatchEmployeeUpdateConfiguration.java#L107

네 오전에 push하지 않은 변경 사항 중 해당 redirection 설정이 불필요하게 중복된다 판단하여 삭제하였습니다.(아직 POST 메소드 사용하여 Request Body에 정보들을 넣는 부분을 완성하지 못하여 변경 사항들을 원격 저장소에 push 하지는 않았습니다.)

**Comment by hnc-cjcho** [comment]
제가 궁금했던것은 그게 뭐하는건지 알고 썼냐는것입니다.

**Comment by DongminKim94** [comment]
> 제가 궁금했던것은 그게 뭐하는건지 알고 썼냐는것입니다.

네. 해당 메소드의 매개변수에 true를 주었을 경우 요청받은 서버의 주소가 변경됬을 때에는 자동으로 변경된 주소로 연결해준다는 것으로 학습하고 해당 메소드를 사용했습니다.(false로 값을 지정한 이유는 자동으로 redirection하지 말도록 하기 위함이었습니다.) 하지만 default값이 true로 설정 되있다는 것을 알게 되었고 만약 서버 주소가 변경이 되었을 경우 자동으로 redirection할 수 있도록 하는 것이 맞는 것 같아 false로 작성해둔 해당 코드는 삭제하였습니다.

**Comment by DongminKim94** [comment]
혹시 몰라 default값도 출력해보았습니다.
![image](https://user-images.githubusercontent.com/42930502/100194217-a4884480-2f38-11eb-9751-34f329d07c05.png)
![image](https://user-images.githubusercontent.com/42930502/100194239-ab16bc00-2f38-11eb-9a68-c05bd9d7b50a.png)

**Comment by hnc-cjcho** [comment]
HttpURLConnection의 getInstanceFollowRedirects() 함수는 instanceFollowRedirects 값을 반환합니다.
https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L382
![image](https://user-images.githubusercontent.com/23737609/100197989-89203800-2f3e-11eb-98c9-286795d9472e.png)

그리고 instanceFollowRedirects  값은 static field인 followRedirects 값을 따릅니다.
https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L298
![image](https://user-images.githubusercontent.com/23737609/100198116-bd93f400-2f3e-11eb-8dfe-d6e64d1972f1.png)

그렇다면 static field인 followRedirects 값은 누가 바꿀 수 있을까요?
static method인 setFollowRedirects 를 누군가가 호출하면 바뀔 수 있습니다.
https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L331
![image](https://user-images.githubusercontent.com/23737609/100198183-dc928600-2f3e-11eb-9f21-e96ed4ccf992.png)

그렇다면 내가 짠 코드 이외의 부분(프레임워크)에서 
HttpURLConnection.setFollowRedirects(false)를 아무도 호출 하지 않았다고 보장할 수 있나요?
당근 보장할 수 없을 것입니다.

그러므로 필요하다면 명시적으로 지정(set)해서 원하는 상태를 반드시 만들어 두어야 합니다.
만약 redirect를 "해야 한다면", 명확하게 "true"를 설정해 주세요.

**Comment by DongminKim94** [comment]
> HttpURLConnection의 getInstanceFollowRedirects() 함수는 instanceFollowRedirects 값을 반환합니다.
> https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L382
> ![image](https://user-images.githubusercontent.com/23737609/100197989-89203800-2f3e-11eb-98c9-286795d9472e.png)
> 
> 그리고 instanceFollowRedirects 값을 누가 바꾸지 않았다면 static field인 followRedirects 값을 따릅니다.
> https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L298
> ![image](https://user-images.githubusercontent.com/23737609/100198116-bd93f400-2f3e-11eb-8dfe-d6e64d1972f1.png)
> 
> 그렇다면 static field인 followRedirects 값은 누가 바꿀 수 있을까요?
> static method인 setFollowRedirects 를 누군가가 호출하면 바뀔 수 있습니다.
> https://github.com/himnay/java7-sourcecode/blob/329bbb33cbe8620aee3cee533eec346b4b56facd/java/net/HttpURLConnection.java#L331
> ![image](https://user-images.githubusercontent.com/23737609/100198183-dc928600-2f3e-11eb-9f21-e96ed4ccf992.png)
> 
> 그렇다면 내가 짠 코드 이외의 부분(프레임워크)에서
> HttpURLConnection.setFollowRedirects(false)를 아무도 호출 하지 않았다고 보장할 수 있나요?
> 당근 보장할 수 없을 것입니다.
> 
> 그러므로 필요하다면 명시적으로 지정(set)해서 원하는 상태를 반드시 만들어 두어야 합니다.
> 만약 redirect를 "해야 한다면", 명확하게 "true"를 설정해 주세요.

상세한 설명 감사합니다. 생각한 부분에 대해서의 설정값을 명확하게 주도록 하겠습니다.
