### ISSUE TITLE
부서이름(인프라팀) 으로 화면에 표출하고 부서이름별(추후에 부서아이디별)로 랜덤 색상 지정하고 해당 부서색을 알맞게 화면에 표출하기

### ISSUE THREAD

**Issue by hyori100** [hancom-io/hanzari#919]

**Comment by AhnHyeonho** [comment]
assignee 지정하고 작업해주세요

**Comment by hyori100** [comment]
층에 사원을 매핑하면 부서맵에 부서객체가 저장된다.
사원을 비우거나 다른 부서의 사원으로 매핑한다면 해당 부서가 층에 남아있지 않는다.

이 상황도 고려하여 작업 예정

**Comment by hyori100** [comment]
> 층에 사원을 매핑하면 부서맵에 부서객체가 저장된다.
> 사원을 비우거나 다른 부서의 사원으로 매핑한다면 해당 부서가 층에 남아있지 않는다.
> 
> 이 상황도 고려하여 작업 예정

--> 사원을 매핑하고 해당 자리를 삭제하면 현재 층 자리리스트에서 자리들에 매핑되어있는 사원의 부서들 중에 해당 자리의 부서와 일치하는 것이 없다면 관리하고있는 현재 층 부서리스트에서 삭제한 후에 DepartmentChips컴포넌트에게 이벤트를 발행한다. 
--> 제일 처음에만 잘 작동이 안되는 버그가 있음. 이를 해결 예정

**Comment by hyori100** [comment]
1. 자리를 비우거나
2. 다른 사원의 자리로 변경하거나

위와 같은 상황에서도 구조 짜야함.

**Comment by hnc-cjcho** [comment]
작업을 하는 도중에, 생각지도 못한 문제가 계속 발견 된다면, 키보드에서 손을 멀리해야 할 때입니다.
사용자의 동작과 보여져야 될 상태, 그리고 이벤트의 흐름을, 종이에 차분히 정리해 보세요.
일부만 정리된 채로 구현하게 되면, 결국 또 생각치도 못한 무언가가 발견될거예요 ^_^
