### ISSUE TITLE
로그인 성공시 로그인한 사용자에 따른 알맞는 화면 로드되게 하기 (권한별로)

### ISSUE THREAD

**Issue by hyori100** [hancom-io/hanzari#921]

**Comment by yunji98** [comment]
현재 Admin, Viewer의 페이지는 만들어둔 상태이고 로그인 후 권한 분류하는 로직을 짜야합니다.
vuex의 store와 라우터를 사용해서 분류할 예정입니다.

**Comment by yunji98** [comment]
로그인 성공시 front로 token만 넘어오고 로그인 한 사람의 authority가 넘어오지 않으므로 이것이 구현되면 
#921 이슈 InProgress로 옮기겠습니다.
