### ISSUE TITLE
Vuex를 이용하여 데이터 (ex. props, eventbus로 관리했던 데이터들...등등)를  하나의 js파일(현재 store.js)로 관리하게 로직 변경하기

### ISSUE THREAD

**Issue by hyori100** [hancom-io/hanzari#922]

**Comment by yunji98** [comment]
이전 로직 : 
초기 로딩때 정해진 하나의 상위 vue 파일에서 한번에 필요한 데이터들 로딩해오는 구조.
이는 props 로 하단 컴포넌트에게 전달해야하는 비효율성이 있었기에 vuex store (전역변수) 로 http requests get 해오는
데이터들을 한번에 관리하는 구조를 만들었습니다.

**Comment by yunji98** [comment]
이때 vuex action을 사용하여 비동기 로직을 처리하였습니다. 이후에 post request 에 관련된 데이터도
전역변수로 저장할 데이터 리스트 등을 한번에 관리할 예정입니다.
