### ISSUE TITLE
Admin 마이페이지에서 건물 버튼을 만들어버튼 클릭으로 각 건물의 자리배치도를 왔다갔다 할 수 있게 만들기

### ISSUE THREAD

**Issue by hyori100** [hancom-io/hanzari#930]
한 회사 또는 그룹은 건물별로 프로그램의 구동을 여러번 하지 않도록

한페이지 안에서 건물을 클릭하여 자리배치도 볼수 있게 하기

**Comment by yunji98** [comment]
#935 와 겹치는 이슈로 판단되어 close하겠습니다.
