### ISSUE TITLE
최초 프로그램 실행시 Super계정이 사원들의 권한을 관리자 또는 매니저의 권한으로 부여할 수 있는 페이지 만들기

### ISSUE THREAD

**Issue by yunji98** [hancom-io/hanzari#936]
권한명이 super인 super계정 제공. 서비스를 제공받는 소비자(회사)에 직접 면대면으로 알려준다. (id: super , pw: 0000)

Super계정의 특징!
- 권한자체 super.
- 모든 employeeList에서는 보이지 않는다.
- 서비스 최초 시작 시 super계정으로 로그인하면 관리자용 권한부여 페이지로 바로 이동. admin으로 지정할 employee들을 정할 수 있다.
- super계정은 삭제 될 수 없다. 
- super계정의 비밀번호를 변경 할 수 있는 페이지 만들려면 만들고 말려면 말기 
- super계정은 관리자용페이지, 뷰어용페이지에 접근 불가

Super계정 개념잡기!
- 그룹웨어에 속해있는 사람의 authority는 모두 viewer이다.
- viewer 권한이 프로그램을 사용하는 최하위 권한이다.
- 원칙적으로 Employee라는 사원 테이블에 속하는 사람들은 그룹웨어에 속한 사람들이다.
- 따라서, 그룹웨어 있는 사람들은 프로그램을 사용할 권한이 있으므로 초기 authority는 NULL이 아닌 viewer이다.

이 맥락상 Super계정이 최초 프로그램 로드시에 권한을 부여할 수 있는 페이지를
**"모든 사원들의 권한을 부여하는 페이지"라는 개념보다는 "Viewer들중에 Admin 혹은 Manager로 권한을 변경할 수 있는 페이지"** (최초의 Admin과 Manager를 설정하는 것이기 때문에 "부여"라는 개념으로도 볼 수 있다.)
로 보는 것이 맞다고 생각하였다.

--> 최초 프로그램 로드시 admin이 존재하기 않기 때문에 이것을 Super계정이 Viewer들 중에 admin으로 권한을 변경할 사람을 지목한다.

**Comment by hyori100** [comment]
권한명이 super인 super계정 제공. 서비스를 제공받는 소비자(회사)에 직접 면대면으로 알려준다. (id: super , pw: 0000)

super계정의 특징
- 권한자체 super.
- 모든 employeeList에서는 보이지 않는다.
- 서비스 최초 시작 시 super계정으로 로그인하면 관리자용 권한부여 페이지로 바로 이동. admin으로 지정할 employee들을 정할 수 있다.
- super계정은 삭제 될 수 없다. 
- super계정의 비밀번호를 변경 할 수 있는 페이지 만들려면 만들고 말려면 말기 
- super계정은 관리자용페이지, 뷰어용페이지에 접근 불가
