### ISSUE TITLE
docker로 db 올리고 공유하기

### ISSUE THREAD

**Issue by AhnHyeonho** [hancom-io/hanzari#952]
지금 공유기설정이 원할하지않아 지속적으로 db를 공유하지못해 아무런 작업도 못하고있는 상황입니다.

현재 저(안현호)의 상황은 공유기가 2중으로 연결되어있으며 (1차공유기 SKB)-(2차공유기-ASUS-wifi)-(노트북) 순으로 연결되어있는 상태입니다.

1. 우선 시도해본 방법으로는 1차공유기에 2차공유기로 포트포워딩을 해주고, 2차공유기에도 wifi로 연결되어있는 노트북으로도 포트포워딩을 해줬습니다. - 실패

2. 1차공유기에서 와이파이로 연결된 노트북의 ip로 바로 포트포워딩을 해줬습니다. - 실패

3. 노트북이 wifi환경이라 유동아이피 문제가 있을 수도 있겠다하여 특정아이피를 할당하는 방식으로 변경하여 1,2번 방법으로 시도해보았습니다. -실패

4. 랜선(유선)으로 연결되는 환경에서는 이더넷 어댑터 정보가 한 개 뜨는 것과 달리 wifi(무선)으로 연결되는 상황(제 노트북의 경우)는 무선LAN 어댑터(wifi), 이더넷 어댑터 vEthernet (Default Switch), 이더넷 어댑터 vEthernet (WSL) 세 가지로 다른 아이피가 나오는 걸 확인하였으며 이 세가지 모두의 경우로 1,2번의 방법을 시도해보았습니다. - 실패

위와같은 경우로 현재 방법으로써는 제가 docker로 db를 띄울 수 없는 상황이라 다른 팀원(랜선으로 연결되어있는 데스크탑이나 노트북을 소유한) 혹은 AWS로 docker를 띄워야 할 것  같습니다.

**Comment by hnc-cjcho** [comment]
vultr 계정을 만들어서 공유드렸습니다. $25 정도의 크레딧이 있지만, 용량 작은 VPS를 만들어서 DB를 돌리는데는 충분할 것입니다.

**Comment by AhnHyeonho** [comment]
팀장님께 vultr 계정을 공유받아 Hanzari VPS를 생성하였고, Docker 설치 및 기존 컨테이너 이관작업을 진행했습니다.
